### ISSUE TITLE
Bootlooping, not even showing bootanimation

### ISSUE THREAD

**Issue by Asmodeus-79** [ChonDoit/treble_cherishos_patches#2]
[console-ramoops-0.zip](https://github.com/ChonDoit/treble_cherishos_patches/files/12188085/console-ramoops-0.zip)

**Comment by Lotybr** [comment]
Which version did you install?

**Comment by ChonDoit** [comment]
> [console-ramoops-0.zip](https://github.com/ChonDoit/treble_cherishos_patches/files/12188085/console-ramoops-0.zip)

Lacks of proper context (Like your device), what build you flashed, etc.

Anyways, 'boringssl-self-check-failed'
99% of the times is due wrong architecture, like you flashed arm64 on a64 device. Also, Magisk is there, remove it first.

**Comment by Asmodeus-79** [comment]
Nah I have solution, the RO build was booted, so I change the img to RW using e2fsck command

**Comment by Asmodeus-79** [comment]
my device facing this issue when flash recent vndklite gsi

**Comment by ChonDoit** [comment]
> Nah I have solution, the RO build was booted, so I change the img to RW using e2fsck command

Ok? But still didn't give context at all

I will assume than you device can't handle remount as rw

**Comment by Asmodeus-79** [comment]
> > Nah I have solution, the RO build was booted, so I change the img to RW using e2fsck command
> 
> Ok? But still didn't give context at all
> 
> I will assume than you device can't handle remount as rw

the gsi with RW build are ok I think.... as long I tried latest GSI with vndklite has that problem, for example the mikuUI by xiaoleegun.... the normal build is in RW too.... it was booted, but when I flash the vndklite version I got that crash
